# Generated by Django 5.2.8 on 2025-11-26 01:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=100000)),
                ('energie_stock', models.IntegerField(default=1000)),
                ('population_totale', models.IntegerField(default=0)),
                ('dernier_calcul', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_directeur', models.BooleanField(default=False, help_text="Est directeur d'un bâtiment spécifique")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nouveau Bâtiment', max_length=100)),
                ('type_batiment', models.CharField(choices=[('MAIRIE', 'Mairie'), ('COMMISSARIAT', 'Commissariat de Police'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble résidentiel'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('COMMERCE', 'Commerce / Supermarché'), ('USINE', 'Usine'), ('BUREAUX', 'Immeuble de Bureaux'), ('CENTRALE', 'Centrale Électrique'), ('PARKING', 'Parking Souterrain')], max_length=20)),
                ('niveau', models.IntegerField(default=1)),
                ('cout_construction', models.IntegerField(default=5000)),
                ('consommation_energie', models.IntegerField(default=10)),
                ('production_argent', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batiments_diriges', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='myapp.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('sante', models.IntegerField(default=100)),
                ('bonheur', models.IntegerField(default=100)),
                ('compte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_citoyen', to=settings.AUTH_USER_MODEL)),
                ('lieu_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='myapp.batiment')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitants', to='myapp.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('VIRE', 'Licencié'), ('DEMISSION', 'Démission')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('initiateur_est_citoyen', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, help_text='Motivation, motif de refus ou de licenciement', null=True)),
                ('batiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='myapp.batiment')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='myapp.citoyen')),
            ],
        ),
    ]
