# Generated by Django 5.2.8 on 2025-11-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='capacite',
            field=models.IntegerField(default=0, help_text="Nombre max d'habitants"),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='lieu_vie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='myapp.batiment'),
        ),
    ]
