# Generated by Django 5.2.8 on 2025-11-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_batiment_capacite_citoyen_lieu_vie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='myapp.ville')),
            ],
        ),
    ]
