# Generated by Django 5.2.8 on 2025-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_is_adjoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='etat',
            field=models.IntegerField(default=100),
        ),
    ]
