# Generated by Django 5.2.8 on 2025-11-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='x',
            field=models.IntegerField(default=0, help_text='Position horizontale (0-9)'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='y',
            field=models.IntegerField(default=0, help_text='Position verticale (0-9)'),
        ),
    ]
