# Generated by Django 5.2.8 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_batiment_hauteur_batiment_largeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='hauteur_map',
            field=models.IntegerField(default=10, help_text='Nombre de cases en hauteur (Y)'),
        ),
        migrations.AddField(
            model_name='ville',
            name='largeur_map',
            field=models.IntegerField(default=10, help_text='Nombre de cases en largeur (X)'),
        ),
    ]
