# Generated by Django 5.2.8 on 2025-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_ville_hauteur_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='epargne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('MAIRIE', 'Mairie'), ('COMMISSARIAT', 'Commissariat de Police'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble résidentiel'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('COMMERCE', 'Commerce / Supermarché'), ('USINE', 'Usine'), ('BUREAUX', 'Immeuble de Bureaux'), ('CENTRALE', 'Centrale Électrique'), ('PARKING', 'Parking Souterrain'), ('CONCESSIONNAIRE', 'Concessionnaire Auto'), ('BANQUE', 'Banque')], max_length=20),
        ),
    ]
