# Generated by Django 5.2.8 on 2025-12-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_candidature_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='motif',
            field=models.CharField(blank=True, help_text='Message optionnel', max_length=100, null=True),
        ),
    ]
