# Generated by Django 5.2.8 on 2025-12-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_candidature_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='date_liberation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='est_en_prison',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('MAIRIE', 'Mairie'), ('COMMISSARIAT', 'Commissariat de Police'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble résidentiel'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('COMMERCE', 'Commerce / Supermarché'), ('USINE', 'Usine'), ('BUREAUX', 'Immeuble de Bureaux'), ('CENTRALE', 'Centrale Électrique'), ('PARKING', 'Parking Souterrain'), ('CONCESSIONNAIRE', 'Concessionnaire Auto'), ('BANQUE', 'Banque'), ('PRISON', "Prison d'État")], max_length=20),
        ),
        migrations.CreateModel(
            name='Casier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200)),
                ('sanction', models.CharField(max_length=100)),
                ('date_jugement', models.DateTimeField(auto_now_add=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casier_judiciaire', to='myapp.citoyen')),
                ('uge_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
