# Generated by Django 5.2.8 on 2025-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_citoyen_date_liberation_citoyen_est_en_prison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='loyer',
            field=models.IntegerField(default=0, help_text='Loyer mensuel pour les locataires'),
        ),
    ]
