# Generated by Django 5.2.8 on 2025-11-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='information',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='information',
            name='titre',
        ),
        migrations.AddField(
            model_name='information',
            name='nom_info',
            field=models.CharField(default=1, max_length=100, verbose_name="Nom de l'information"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='valeur_info',
            field=models.CharField(default=0, max_length=255, verbose_name='Valeur'),
            preserve_default=False,
        ),
    ]
