# Generated by Django 5.2.8 on 2025-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_information_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adjoint',
            field=models.BooleanField(default=False, help_text='Est adjoint au Maire (Droit de construction)'),
        ),
    ]
