# Generated by Django 5.2.8 on 2025-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='argent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='vehicule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('MAIRIE', 'Mairie'), ('COMMISSARIAT', 'Commissariat de Police'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble résidentiel'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('COMMERCE', 'Commerce / Supermarché'), ('USINE', 'Usine'), ('BUREAUX', 'Immeuble de Bureaux'), ('CENTRALE', 'Centrale Électrique'), ('PARKING', 'Parking Souterrain'), ('CONCESSIONNAIRE', 'Concessionnaire Auto')], max_length=20),
        ),
    ]
