# Generated by Django 5.2.8 on 2025-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_batiment_x_batiment_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='hauteur',
            field=models.IntegerField(default=1, help_text='Taille en Y'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='largeur',
            field=models.IntegerField(default=1, help_text='Taille en X'),
        ),
    ]
