# Generated by Django 5.2.8 on 2025-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ville_hauteur_map_ville_largeur_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='hauteur_map',
            field=models.IntegerField(default=5, help_text='Nombre de cases en hauteur (Y)'),
        ),
    ]
