# Generated by Django 5.2.8 on 2025-12-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_citoyen_epargne_alter_batiment_type_batiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('type_trans', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('VIREMENT', 'Virement'), ('SALAIRE', 'Salaire'), ('IMPOT', 'Impôts')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='myapp.citoyen')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='myapp.citoyen')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ville')),
            ],
        ),
    ]
