# Generated by Django 5.2.8 on 2025-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_transaction_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('VIRE', 'Licencié'), ('DEMISSION', 'Démission'), ('VIREMENT', 'Virement Reçu'), ('DOLEANCE', 'Doléance Citoyenne')], default='EN_ATTENTE', max_length=20),
        ),
    ]
