# Generated by Django 5.2.8 on 2025-12-09 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_batiment_loyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casier',
            name='uge_par',
        ),
        migrations.AddField(
            model_name='casier',
            name='juge_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casier',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casiers', to='myapp.citoyen'),
        ),
        migrations.AlterField(
            model_name='casier',
            name='motif',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casier',
            name='sanction',
            field=models.CharField(max_length=255),
        ),
    ]
