# Generated by Django 5.2.8 on 2025-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_casier_uge_par_casier_juge_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='prochain_loyer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
