# Generated by Django 5.2.8 on 2025-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_citoyen_prochain_loyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='nom_voiture',
            field=models.CharField(blank=True, default='Aucune', max_length=100, null=True),
        ),
    ]
