# Generated by Django 5.2.8 on 2025-12-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_batiment_type_batiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation en degrés (0 ou 90)'),
        ),
    ]
