# Generated by Django 5.2.8 on 2025-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_batiment_type_batiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='type_batiment',
            field=models.CharField(choices=[('MAIRIE', 'Mairie'), ('COMMISSARIAT', 'Commissariat de Police'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble résidentiel'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('COMMERCE', 'Commerce / Supermarché'), ('USINE', 'Usine'), ('BUREAUX', 'Immeuble de Bureaux'), ('CENTRALE', 'Centrale Électrique'), ('PARKING', 'Parking Souterrain'), ('CONCESSIONNAIRE', 'Concessionnaire Auto'), ('BANQUE', 'Banque'), ('PRISON', "Prison d'État"), ('ROUTE', 'Route Droite'), ('ROUTE_VIRAGE', 'Route Virage'), ('STADE', 'Stade')], max_length=20),
        ),
    ]
